### ISSUE TITLE
Different implementation of softmax_loss

### ISSUE THREAD

**Issue by MARD1NO** [dlsyscourse/hw0#5]
Hi, currently I try to finish the homwork0, and in softmax loss, I found my implementation will be stuck in large data(Like the test_simple_ml.py use 60000 samples to compute)

```python
softmax_result = np.exp(Z[range(Z.shape[0]), y]) / np.sum(np.exp(Z), axis=1, keepdims=True)
return np.mean(-np.log(softmax_result))
```

Then I found a nice implementation from https://github.com/xingyu-long/hw0

```python
def softmax_loss(Z, y):
    def softmax(x):
            return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)
    
        return np.mean(-np.log(softmax(Z)[np.indices(y.shape)[0], y]))
```
I use it and it won't stuck in test. I just wondering is there exists low effective operations in my implementation?

**Comment by ashertrockman** [comment]
For both implementations, I recommend applying `log` to the `exp`s analytically when possible (otherwise there can be some numerical trouble).

In the future, please don't post your solutions publicly when asking questions (try to ask the question without posting the solution). We also prefer you post on the class forum if possible.
